### ISSUE TITLE
No update if new progress is lower than previous one

### ISSUE THREAD

**Issue by falaix** [MitchellMalleo/VAProgressCircle#1]
If the new progress (e. g. 50) is lower than the previous progress (e. g. 60) than there is no animation and also the progress of the line is not being decreased. It simply keeps the same.

**Comment by MitchellMalleo** [comment]
Hi dagobert-duck,

At the current time, there is no functionality to reverse your progress. I'll label it as an enhancement for future open source development. (:

**Comment by falaix** [comment]
Thanks for your quick response.

Is there an easy way to reset the progress (without any animation) to zero? So that I can use `- (void)setProgress:(int)progress` again? Thanks.

**Comment by MitchellMalleo** [comment]
[self.progressCircle removeFromSuperview]; 
self.progressCircle = [[VAProgressCircle alloc] initWithFrame:CGRectMake(80, 80, 200, 200)];
//Any other property modifications
[self.view addSubview:self.progressCircle];

This is a pretty basic example, but should get the job done. If you have the repository cloned, a similar example should exist in the sample project. Hope this helps.
